### ISSUE TITLE
My micromamba role

### ISSUE THREAD

**Issue by maresb** [mamba-org/build-locally-ansible#1]
Hey there @wolfv and @atrawog, I did something similar to your `mamba.yml` in https://github.com/maresb/ansible-micromamba-role.  Does it make sense to consolidate our efforts?

**Comment by wolfv** [comment]
Hi @maresb 

wow, looks great! I think @atrawog (our Ansible specialist) might be able to give a more detailed review :)

I think yes, consolidating our efforts would be nice. Ideally we end up with something that we can publish to Ansible Galaxy so that it can be easily used as "plugin".

Would you be open to the idea of moving your ansible role to `mamba-org` (you would keep all admin rights, of course)? It could be nice to have it in the same `org` as many of these other efforts (`micromamba-docker`, `provision-with-micromamba`, ...).

**Comment by maresb** [comment]
Ya, sounds good to me! I'm an Ansible beginner, so I could really benefit from an expert review. I have already published my role to Ansible Galaxy. (See the "homepage" link of my repo.)

Also it'd be interesting to get some feedback on my downstream use of this role. I'm using it to create a base environment owned by root so that one can `sudo mamba install …` or `mamba create --name user-environment`, and it seems to work very well so far. (That way I can use it to initialize multiuser EC2 instances for Python development.) I can share more details if desired.

**Comment by maresb** [comment]
I was also thinking that it could be useful to have an Ansible module for `conda`/`mamba` initializing a home directory. (I initialize `/etc/skel` before creating user accounts.) It's an idempotent operation, but with Ansible I find it awkward to invoke via an external executable, and then figure out whether or not the state should be "changed".

**Comment by atrawog** [comment]
Hi @maresb

Your micromamba-role looks like it's pretty well written and it definitely would make sense to consolidate efforts and I will get in touch with you if I bump into any errors testing your role.

**Comment by maresb** [comment]
@atrawog, great! Let me know how you'd like to move forward after your tests. If you want to clone my repo to mamba-org then I'll try to figure out how to migrate Galaxy.

I noticed for example that I should have called it `ansible-role-micromamba` instead of `ansible-micromamba-role`. I think there are various other things which are slightly out of spec which would be nice to clean up.

**Comment by atrawog** [comment]
I've tested the `ansible-micromamba-role` and it works pretty well. The only thing we have come to terms is how to setup and activate micromamba environment for non-root users in Ansible and adopt the role and all the scripts that are using it accordingly.

**Comment by maresb** [comment]
Great! I'll share how I've been using this role on Ubuntu in EC2 and Docker. Sorry that there's quite a bit here. Please let me know if anything seems missing or if you'd like me to clarify anything.

I haven't integrated these things into my current role because I want to keep things as unifunctional as possible. And because I don't have a good sense of what would be good boundaries for various steps. I'd really appreciate some fresh eyes on this.

## Configure system environment and sudo

[EDIT: published to conda_system_install](https://github.com/maresb/micromamba-role-example/blob/master/ansible/roles/conda_system_install/tasks/main.yaml)

Then `secure_path` consists of the single line

```text
Defaults        secure_path="/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
```
(This is Ubuntu's default `secure_path` with `/opt/conda/bin` prepended.)

This allows the users with sudo to run binaries (e.g. `mamba`) from the prefix as root. You can do `sudo mamba install x` to adjust the base environment.

## Initialize home directories

For initializing home directories, I have two approaches. The one I'm currently using consists of a role called `initialize_home` which is:

[EDIT: published to initialize_home](https://github.com/maresb/micromamba-role-example/blob/master/ansible/roles/initialize_home/tasks/main.yaml)

And then `_activate-conda` is

[EDIT: published to _activate-conda](https://github.com/maresb/micromamba-role-example/blob/master/ansible/roles/initialize_home/files/_activate-conda)

Before creating any users, I run this role on `/root` and `/etc/skel`. (Note: `/etc/skel` is the home directory template for newly created users.)

[EDIT: published to initialize_root_and_skel_playbook](https://github.com/maresb/micromamba-role-example/blob/master/ansible/initialize_root_and_skel_playbook.yaml)

## Alternative solution for activating new users

My previous solution involved the following idempotent script (unfortunately not Ansible-ized) for updating `/etc/skel/.bashrc` which uses the original `conda init` and `mamba init` commands:

[EDIT: published to alternative-user-init](https://github.com/maresb/micromamba-role-example/blob/master/alternative-user-init.sh)

**Comment by maresb** [comment]
Probably I should put all this into a Docker container so that you can see more clearly how it works and test the resulting environment. I'm busy at the moment, but I could probably throw something together soon.

**Comment by maresb** [comment]
Okay, I threw everything together into a Dockerfile and published it to [micromamba-role-example](https://github.com/maresb/micromamba-role-example).

Hopefully that makes it easy to understand my setup. Let me know if you have any questions!

**Comment by maresb** [comment]
Thanks @wolfv for adding me to mamba-org, that's quite an honor!

Shall I create a new `ansible-role-micromamba` repository under `mamba-org`, register it with Ansible Galaxy, and archive my current repo?

**Comment by wolfv** [comment]
As you like! I'd suggest to move the current repo, and then rename it (to keep the commit history and issues  etc).

Regarding ansible Galaxy I don't know what we need to do. Happy to look into that when I'm back on Wednesday. Would it make sense to have a mamba org with multiple maintainers there, too?

**Comment by maresb** [comment]
Hi all, I'm looking into how to make this happen.

It seems that the first thing we need is a "namespace" for mamba-org in Ansible Galaxy. A "namespace" is the part before the period in the name `maresb.micromamba`, and defaults to your GitHub username. We need to [request a namespace for a GitHub organization](https://galaxy.ansible.com/docs/contributing/namespaces.html#requesting-additional-namespaces), which is done via pull request for human review.

I was about to submit the PR but I noticed a few things which I figured I should run by you guys:

* I would appoint @atrawog, @wolfv, and @maresb as namespace administrators. However, to be added as an administrator, you must first have a Galaxy account. I checked, and @wolfv does not yet have an account. (It's very easy to set up since authentication is managed via GitHub. Just visit galaxy.ansible.com, click "Login" and link your GitHub account.)
* Do you agree with the name and description? It seems that `-` [may not be a valid character](https://galaxy.ansible.com/docs/contributing/namespaces.html#namespace-limitations), so we may have to go with `mambaorg` or `mamba_org`. (I notice for example that the DockerHub account is `mambaorg`.) Do you have a preference?

Here is my draft PR for submission [here](https://github.com/ansible/galaxy/issues/new?template=New_namespace.md):

Issue title:
> namespace: mambaorg

Issue text:
```markdown
## Namespace Request
Namespace: mambaorg

##### Description
<!--- One line description, will be visible in Galaxy--->
The Fast Cross-Platform Package Manager, and related tools

##### GitHub Org Link
<!--- Please provide us with a link to your GitHub org -->
<https://github.com/mamba-org>

##### Admins
<!--- Please provide us with a list of Galaxy users who you would like to set up as admins on this namespace -->
<!--- Please ensure each admin has logged into galaxy.ansible.com, which will create their user account -->
@atrawog, @wolfv, @maresb
```

**Comment by wolfv** [comment]
Awesome. I just made the account on Galaxy. 

I think `mambaorg` would be good to be consistent with dockerhub!

**Comment by maresb** [comment]
Great! I was just thinking, another possibility for the namespace could simply be `mamba`. Or do you view "mamba-org" as an official entity?

Also, do you agree with this description?
> The Fast Cross-Platform Package Manager, and related tools

If so then I'll submit the PR to Galaxy.

**Comment by wolfv** [comment]
Maybe we want to have roles for quetz or boa at some point in the future? I think mambaorg is fine :)

**Comment by wolfv** [comment]
Description is fine with me, too

**Comment by maresb** [comment]
Great! Submitted: https://github.com/ansible/galaxy/issues/2827

**Comment by maresb** [comment]
Continued in https://github.com/ansible/galaxy/issues/2829

**Comment by wolfv** [comment]
cool!

**Comment by maresb** [comment]
Slowly moving this forward... I just initiated a request for Ansible Galaxy access to mamba-org as per instructions in ansible/galaxy#2829:

![image](https://user-images.githubusercontent.com/15216687/143487380-0615b39a-b275-4287-a9b9-1b5d14488ed0.png)

**Comment by maresb** [comment]
I'm still waiting for the access request to be approved by the mamba-org administrator.

Once we get mamba-org linked, I've been thinking about the next steps. I believe that an old copy of the role will always exist under my namespace. I think the next steps should be...

* release a new patch version to update the README with a notice that further development will continue on mamba-org. This will remain as the last version under my namespace, but link to mamba-org.
* rename my repo from `ansible-micromamba-role` to `ansible-role-micromamba` in accordance with standard conventions
* transfer repo ownership to mamba-org
* release a new patch version which updates the README to remove the migration notice
* import the repo into the mamba-org Galaxy namespace

**Comment by wolfv** [comment]
Sounds like a good plan! Thanks for tackling this @maresb :)

**Comment by maresb** [comment]
@wolfv, my request to mamba-org's GitHub admin for granting access to the Ansible Galaxy OAuth App is still pending (see the screenshot above).

Are you the admin of mamba-org's GitHub account? If so, could you please check your e-mails? Thanks!

**Comment by wolfv** [comment]
Done! Sorry, I move all GitHub emails out of the inbox. There are just too many :)

**Comment by maresb** [comment]
Thanks @wolfv! The migration to mamba-org went very smoothly and is now finished. The new links are

<https://github.com/mamba-org/ansible-role-micromamba>
<https://galaxy.ansible.com/mambaorg/micromamba>

I also migrated and tested [my Docker usage example](https://github.com/maresb/micromamba-role-example) which works flawlessly with the new namespace.
